apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  namespace: databases
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      imagePullSecrets:
        - name: acr-secret 
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: mysql-server
          image: containerregistryunique.azurecr.io/mysql:0.1.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "ecommerce_db"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "Pass123."

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  namespace: databases
spec:
  selector:
    app: mysql-server
  ports:
    - name: http
      port: 3306
      targetPort: 3306
  type: ClusterIP